version: '3'
services:
  web:
    build: ./web
    depends_on:
      - db
    volumes:
      - ..:/var/www/html:cached
      - ./web/apache2.conf:/etc/apache2/apache2.conf
      - ./web/php.ini:/usr/local/etc/php/php.ini
    user: '1000:1000'
    ports:
      - '8080:80'
    restart: always
    working_dir: /var/www/html
  db:
    build: ./mysql
    environment:
      MYSQL_DATABASE: docker_db
      MYSQL_USER: docker_user
      MYSQL_PASSWORD: docker_pass
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/ddl:/var/lib/docker-entrypoeint-initdb.d
      - ./mysql/db:/var/lib/mysql
    user: '1000:1000'
    ports:
      - '3306:3306'
    restart: always
  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - '3000:8080'
    restart: always